/**
 * MODULES that are defined in the AMAZE
 */
export enum MODULES {
    USER_MANAGEMENT = "USER_MANAGEMENT",
    AMAZE_TOUCH = "AMAZE_TOUCH",
    BOND = "BOND",
    AMAZE_MOBILE = "AMAZE_MOBILE",
    CODING_REVIEW = "CODING_REVIEW"
}